remove default log level
kubernetes-sigs/apiserver-network-proxy pull request #181
Opened 2021-03-04 04:21 UTC by huiwq1990

This PR remove default klog level, and allow user set custom log level for debug case.

2021-04-05 17:45 UTC, Jefftree commented
Hello thank you for your PR. It is already possible to override the default logging level by passing in a `--v` parameter.  I'm curious about why this change is needed?

2021-04-22 02:05 UTC, huiwq1990 commented
@Jefftree sorry, my mistake. The flag `--v` work fine. I change my PR, use  `component-base` to operator flag.

2021-08-06 21:57 UTC, jdnurme requested changes

2021-08-06 21:57 UTC, jdnurme commented on cmd/server/main.go
> +	flags.AddGoFlagSet(local)
Can you run `./bin/proxy-server --help` before and after your change, and provide the diff to this PR? We want to makes sure we aren't clobbering flags.

2021-08-06 21:57 UTC, jdnurme commented on cmd/agent/main.go
> +	logs.InitLogs()
Can you run `./bin/proxy-agent --help` before and after your change, and provide the diff to this PR? We want to makes sure we aren't clobbering flags.

2022-01-03 23:23 UTC, closed without merging